services:
  api-gateway:
    build:
      ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - storage-service
  storage-service:
    build:
      ./storage-service
    ports:
      - "9090:9090" #gRPC
